### PR TITLE
Move from LightGraphs to Graphs

### PR DESCRIPTION
**Pull request by storopoli**
This is a minimal update. I have not added any funcionality.

All 71 tests run OK.

This also adds a missing `Project.toml` in the original version.
I've copied the same `.gitignore` as `Graphs.jl`

### CODE REVIEW

**Comment by storopoli** [comment]
I also need help to register this new version in Julia Register. If anybody could help I much appreciate.

**Comment by matbesancon** [comment]
you can merge #4 into yours first and we should be good

**Comment by storopoli** [comment]
OK, the tests are running all ok. If you are all right we can merge and we can work towards a new release. This I will need help I don't know how to do it. I don't see any TagBot in this repo.

**Comment by storopoli** [comment]
I can deal with the conflits but I do not have write access.

**Comment by matbesancon** [comment]
you don't need write access, just merging origin master into your branch (also, usually recommended to branch and not use the master one of your fork)

**Comment by storopoli** [comment]
> you don't need write access, just merging origin master into your branch (also, usually recommended to branch and not use the master one of your fork)

Yes, now I do understand that. 🙄

**Comment by matbesancon** [comment]
thanks!

**Comment by storopoli** [comment]
Great thanks! What do we need to launch a new release?

**Pull request merged**
